-- MySQL Script generated by MySQL Workbench
-- Thu May  8 06:53:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema baseProyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baseProyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baseProyecto` DEFAULT CHARACTER SET utf8 ;
USE `baseProyecto` ;

-- -----------------------------------------------------
-- Table `baseProyecto`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseProyecto`.`Rol` (
  `idROL` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idROL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseProyecto`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseProyecto`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `Rol_idROL` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Rol1_idx` (`Rol_idROL` ASC) ,
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`Rol_idROL`)
    REFERENCES `baseProyecto`.`Rol` (`idROL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseProyecto`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseProyecto`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `contacto` INT NOT NULL,
  `estado` TINYINT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idProveedor`),
  INDEX `fk_Proveedor_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_Proveedor_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `baseProyecto`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseProyecto`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseProyecto`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseProyecto`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseProyecto`.`Producto` (
  `idProducto` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(30) NOT NULL,
  `imagen` BLOB(1) NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Categoria1_idx` (`Categoria_idCategoria` ASC) ,
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `baseProyecto`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseProyecto`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseProyecto`.`Inventario` (
  `idInventario` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  `stockMinimo` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`idInventario`),
  INDEX `fk_Inventario_Producto1_idx` (`Producto_idProducto` ASC) ,
  CONSTRAINT `fk_Inventario_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `baseProyecto`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseProyecto`.`movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseProyecto`.`movimiento` (
  `idmovimiento` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `Inventario_idInventario` INT NOT NULL,
  PRIMARY KEY (`idmovimiento`),
  INDEX `fk_movimiento_Inventario1_idx` (`Inventario_idInventario` ASC) ,
  CONSTRAINT `fk_movimiento_Inventario1`
    FOREIGN KEY (`Inventario_idInventario`)
    REFERENCES `baseProyecto`.`Inventario` (`idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseProyecto`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseProyecto`.`Pedido` (
  `idPedido` INT NOT NULL,
  `total` DECIMAL NOT NULL,
  `estado` TINYINT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_Pedido_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `baseProyecto`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseProyecto`.`Pedido_has_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseProyecto`.`Pedido_has_Producto` (
  `Pedido_idPedido` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Producto_idProducto`),
  INDEX `fk_Pedido_has_Producto_Producto1_idx` (`Producto_idProducto` ASC) ,
  INDEX `fk_Pedido_has_Producto_Pedido1_idx` (`Pedido_idPedido` ASC) ,
  CONSTRAINT `fk_Pedido_has_Producto_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `baseProyecto`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `baseProyecto`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseProyecto`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseProyecto`.`Pago` (
  `idPago` INT NOT NULL,
  `total` DECIMAL NOT NULL,
  `fechaPago` DATE NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `fk_Pago_Pedido1_idx` (`Pedido_idPedido` ASC) ,
  CONSTRAINT `fk_Pago_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `baseProyecto`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseProyecto`.`tipoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseProyecto`.`tipoPago` (
  `idtipoPago` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `monto` DECIMAL NOT NULL,
  `Pago_idPago` INT NOT NULL,
  PRIMARY KEY (`idtipoPago`),
  INDEX `fk_tipoPago_Pago1_idx` (`Pago_idPago` ASC) ,
  CONSTRAINT `fk_tipoPago_Pago1`
    FOREIGN KEY (`Pago_idPago`)
    REFERENCES `baseProyecto`.`Pago` (`idPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
